### ISSUE TITLE
The demo app is crashing due to java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.

### ISSUE THREAD

**Issue by quangtruongdit** [google-pay/compose-pay-button#15]
Hi there,

I have just download and build the demo app from my android device. But the app is crashed at the started time. Could you please support?
I upload here the error from my ide.
<img width="2343" alt="image" src="https://github.com/google-pay/compose-pay-button/assets/113823159/39fe1fc0-c7d5-41a8-9852-c19c89cde837">

My device: Vinsmart with Android 10 and google play service version 23.48.16

My though: The google play service version cause this error, but this version is new one from google. 

Thank you so much

**Comment by dmengelt** [comment]
thanks for reporting this @quangtruongdit 

We are aware and a permanent fix for this issue will be rolled out to users by a Play Services update in January.
You can mitigate the issue by disabling Google Pay for users with an Android version <= 10:
```kotlin
if (android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.Q) {
  // Do not display a Google Pay button
}
```

**Comment by quangtruongdit** [comment]
Thanks @dmengelt for your support. I will check it again when the new play service version released.

**Comment by Separd-ui** [comment]
I'am using "com.google.android.gms:play-services-wallet:19.2.1", but also getting crash on Android 10. What's interesting It was working before, but now some users with Xiaomi devices get the crash, but I can't reproduce It on emulator, the only thing that I get is :
"Google Play services out of date for  Requires 232100000 but found 202414019
2024-01-09 12:13:23.791  7949-7949  PayButton                                       E  Failed to create latest buttonView: Google Play Services version is outdated."

**Comment by dmengelt** [comment]
@Separd-ui the fix (new Google Play service version) was not yet rolled out. 

Using the newest `play-services-wallet` unfortunately won't fix the issue. You have to wait until the new Play services version hits your device.

**Comment by dmengelt** [comment]
@quangtruongdit / @Separd-ui 

The issue is fixed with Play Services version `24.02.13` hitting 100% rollout this week.

**Comment by hardik349** [comment]
I am testing my application on Android 14 and google play services 24.03.15 still getting the same runtime error while using google maps in android application
![Screenshot (24)](https://github.com/google-pay/compose-pay-button/assets/74033252/1032347f-840e-4c29-b204-576ac864641d)

**Comment by hardik349** [comment]
I am testing my application on Android 14 and google play services 24.03.15 still getting the same runtime error while using google maps in android application
![Screenshot (24)](https://github.com/google-pay/compose-pay-button/assets/74033252/e70711ff-59e4-4735-b2ef-4fc7414957e7)

**Comment by dmengelt** [comment]
@hardik349 this is a Google Pay repository and the bug got fixed with the rollout of `24.02.13`.
